// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"titan-vm/vms/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/vm/create",
				Handler: createVMHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vm/delete",
				Handler: deleteVMHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vm/image/list",
				Handler: listImageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vm/libvirt/volume/create",
				Handler: createVolWithLibvirtHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vm/list",
				Handler: listVMInstanceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vm/multipass/exec",
				Handler: multipassExecHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vm/start",
				Handler: startVMHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vm/stop",
				Handler: stopVMHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vm/update",
				Handler: updateVMHandler(serverCtx),
			},
		},
	)
}
