Name: titan-tunnel-server
Host: 0.0.0.0
Port: 8888
Redis:
  Host: 127.0.0.1:6379
JwtAuth:
  AccessSecret: ef61299a-53e6-11f0-87d4-e72f7b1c2247
  AccessExpire: 86400
Socks5:
  Addr: 0.0.0.0:5000
  UDPServerIP: 127.0.0.1
  UDPPortStart: 7100
  UDPPortEnd: 7200
  EnableAuth: true
  ## 4 seconds
  ### example: dail dest timeout
  TCPTimeout: 4
  ### 120 seconds
  ### udp proxy timeout if no data transfer
  ### client udp proxy timeout is 60s
  UDPTimeout: 120
Log:
  stat: false
  level: debug   

ServerURL: ws://localhost:8888/ws/node
PopID: 37c8e134-5be2-11f0-8909-00163e0ced7c
Pops: 
  - ID: 37c8e134-5be2-11f0-8909-00163e0ced7c
    Area: Korea
    Socks5Addr: localhost:5000