// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type DeleteUserCache struct {
	UserName string `json:"user_name"`
}

type NodeWSReq struct {
	NodeId string `form:"id"`
	OS     string `form:"os"`
}
