// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	"titan-tunnel/server/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/node/access/token",
					Handler: getNodeAccessTokenHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/server/info",
					Handler: getServerInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/cache/delete",
					Handler: deleteUserCacheHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/ws/node",
					Handler: nodeWSHandler(serverCtx),
				},
			}...,
		),
	)
}
