// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义消息类型枚举
type MessageType int32

const (
	MessageType_UNKNOWN              MessageType = 0
	MessageType_CONTROL              MessageType = 1
	MessageType_PROXY_SESSION_CREATE MessageType = 2
	MessageType_PROXY_SESSION_DATA   MessageType = 3
	MessageType_PROXY_SESSION_CLOSE  MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CONTROL",
		2: "PROXY_SESSION_CREATE",
		3: "PROXY_SESSION_DATA",
		4: "PROXY_SESSION_CLOSE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":              0,
		"CONTROL":              1,
		"PROXY_SESSION_CREATE": 2,
		"PROXY_SESSION_DATA":   3,
		"PROXY_SESSION_CLOSE":  4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_INVALID_COMMAND CommandType = 0
	CommandType_DownloadImage   CommandType = 1
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "INVALID_COMMAND",
		1: "DownloadImage",
	}
	CommandType_value = map[string]int32{
		"INVALID_COMMAND": 0,
		"DownloadImage":   1,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

type DownloadTaskAction int32

const (
	DownloadTaskAction_ACTION_UNKNOWN DownloadTaskAction = 0
	DownloadTaskAction_START          DownloadTaskAction = 1
	DownloadTaskAction_STOP           DownloadTaskAction = 2
	DownloadTaskAction_DELETE         DownloadTaskAction = 3
)

// Enum value maps for DownloadTaskAction.
var (
	DownloadTaskAction_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "START",
		2: "STOP",
		3: "DELETE",
	}
	DownloadTaskAction_value = map[string]int32{
		"ACTION_UNKNOWN": 0,
		"START":          1,
		"STOP":           2,
		"DELETE":         3,
	}
)

func (x DownloadTaskAction) Enum() *DownloadTaskAction {
	p := new(DownloadTaskAction)
	*p = x
	return p
}

func (x DownloadTaskAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownloadTaskAction) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (DownloadTaskAction) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x DownloadTaskAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownloadTaskAction.Descriptor instead.
func (DownloadTaskAction) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

// 定义命令消息体
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=pb.CommandType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_INVALID_COMMAND
}

func (x *Command) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 目标地址
type DestAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestAddr) Reset() {
	*x = DestAddr{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestAddr) ProtoMessage() {}

func (x *DestAddr) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestAddr.ProtoReflect.Descriptor instead.
func (*DestAddr) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *DestAddr) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *DestAddr) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// 定义通用消息体
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=pb.MessageType" json:"type,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CmdDownloadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Md5           string                 `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdDownloadImageRequest) Reset() {
	*x = CmdDownloadImageRequest{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdDownloadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdDownloadImageRequest) ProtoMessage() {}

func (x *CmdDownloadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdDownloadImageRequest.ProtoReflect.Descriptor instead.
func (*CmdDownloadImageRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *CmdDownloadImageRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CmdDownloadImageRequest) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *CmdDownloadImageRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CmdDownloadTaskControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdDownloadTaskControlResponse) Reset() {
	*x = CmdDownloadTaskControlResponse{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdDownloadTaskControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdDownloadTaskControlResponse) ProtoMessage() {}

func (x *CmdDownloadTaskControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdDownloadTaskControlResponse.ProtoReflect.Descriptor instead.
func (*CmdDownloadTaskControlResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *CmdDownloadTaskControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CmdDownloadTaskControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DownloadTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5,proto3" json:"md5,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTask) Reset() {
	*x = DownloadTask{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTask) ProtoMessage() {}

func (x *DownloadTask) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTask.ProtoReflect.Descriptor instead.
func (*DownloadTask) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadTask) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadTask) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *DownloadTask) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type CmdDownloadTaskListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*DownloadTask        `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdDownloadTaskListResponse) Reset() {
	*x = CmdDownloadTaskListResponse{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdDownloadTaskListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdDownloadTaskListResponse) ProtoMessage() {}

func (x *CmdDownloadTaskListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdDownloadTaskListResponse.ProtoReflect.Descriptor instead.
func (*CmdDownloadTaskListResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *CmdDownloadTaskListResponse) GetTasks() []*DownloadTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type DownloadTaskControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        DownloadTaskAction     `protobuf:"varint,2,opt,name=action,proto3,enum=pb.DownloadTaskAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTaskControlRequest) Reset() {
	*x = DownloadTaskControlRequest{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTaskControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTaskControlRequest) ProtoMessage() {}

func (x *DownloadTaskControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTaskControlRequest.ProtoReflect.Descriptor instead.
func (*DownloadTaskControlRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadTaskControlRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadTaskControlRequest) GetAction() DownloadTaskAction {
	if x != nil {
		return x.Action
	}
	return DownloadTaskAction_ACTION_UNKNOWN
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x02pb\"B\n" +
	"\aCommand\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.pb.CommandTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"8\n" +
	"\bDestAddr\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"g\n" +
	"\aMessage\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.pb.MessageTypeR\x04type\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"Q\n" +
	"\x17CmdDownloadImageRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x10\n" +
	"\x03md5\x18\x02 \x01(\tR\x03md5\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"T\n" +
	"\x1eCmdDownloadTaskControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\fDownloadTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"E\n" +
	"\x1bCmdDownloadTaskListResponse\x12&\n" +
	"\x05tasks\x18\x01 \x03(\v2\x10.pb.DownloadTaskR\x05tasks\"\\\n" +
	"\x1aDownloadTaskControlRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x06action\x18\x02 \x01(\x0e2\x16.pb.DownloadTaskActionR\x06action*r\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aCONTROL\x10\x01\x12\x18\n" +
	"\x14PROXY_SESSION_CREATE\x10\x02\x12\x16\n" +
	"\x12PROXY_SESSION_DATA\x10\x03\x12\x17\n" +
	"\x13PROXY_SESSION_CLOSE\x10\x04*5\n" +
	"\vCommandType\x12\x13\n" +
	"\x0fINVALID_COMMAND\x10\x00\x12\x11\n" +
	"\rDownloadImage\x10\x01*I\n" +
	"\x12DownloadTaskAction\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\t\n" +
	"\x05START\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x032\t\n" +
	"\amessageB\aZ\x05../pbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_message_proto_goTypes = []any{
	(MessageType)(0),                       // 0: pb.MessageType
	(CommandType)(0),                       // 1: pb.CommandType
	(DownloadTaskAction)(0),                // 2: pb.DownloadTaskAction
	(*Command)(nil),                        // 3: pb.Command
	(*DestAddr)(nil),                       // 4: pb.DestAddr
	(*Message)(nil),                        // 5: pb.Message
	(*CmdDownloadImageRequest)(nil),        // 6: pb.CmdDownloadImageRequest
	(*CmdDownloadTaskControlResponse)(nil), // 7: pb.CmdDownloadTaskControlResponse
	(*DownloadTask)(nil),                   // 8: pb.DownloadTask
	(*CmdDownloadTaskListResponse)(nil),    // 9: pb.CmdDownloadTaskListResponse
	(*DownloadTaskControlRequest)(nil),     // 10: pb.DownloadTaskControlRequest
}
var file_message_proto_depIdxs = []int32{
	1, // 0: pb.Command.type:type_name -> pb.CommandType
	0, // 1: pb.Message.type:type_name -> pb.MessageType
	8, // 2: pb.CmdDownloadTaskListResponse.tasks:type_name -> pb.DownloadTask
	2, // 3: pb.DownloadTaskControlRequest.action:type_name -> pb.DownloadTaskAction
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
