Name: titan-tunnel-server
Host: 0.0.0.0
Port: 8000
Redis:
  Host: 127.0.0.1:6379
JwtAuth:
  AccessSecret: ef61299a-53e6-11f0-87d4-e72f7b1c2247
  AccessExpire: 86400
Log:
  stat: false
  level: debug   
Pops: 
  - ID: 14bf4178-6160-11f0-a0c5-00163e023040
    Area: Korea
    Socks5Addr: localhost:5000
    WSServer: ws://localhost:8080/ws/node
    RpcClient:
      Target: localhost:8081
      Timeout: 30000