Name: titan-tunnel-server
Host: 0.0.0.0
Port: 8000
Redis:
  Host: 127.0.0.1:6379
JwtAuth:
  AccessSecret: ef61299a-53e6-11f0-87d4-e72f7b1c2247
  AccessExpire: 86400
Log:
  stat: false
  level: debug   
Pops: 
  - ID: 37c8e134-5be2-11f0-8909-00163e0ced7c
    Area: Korea
    Socks5Addr: localhost:5000
    WSServer: ws://localhost:8888/ws/node
    RpcClient:
      Target: localhost:8080
      Timeout: 30000