Name: titan-tunnel-server
Host: 0.0.0.0
Port: 41004
Redis:
  Host: 127.0.0.1:6379
JwtAuth:
  AccessSecret: ef61299a-53e6-11f0-87d4-e72f7b1c2247
  AccessExpire: 86400
Log:
  stat: false
  level: debug   
Pops: 
  - Id: 14bf4178-6160-11f0-a0c5-00163e023040
    Area: Korea
    RpcClient:
      Target: localhost:8080
      Timeout: 30000